import { useMemo } from 'react';
import type { BuildingArchetype } from '@/schemas/building.schema';
import { hashString } from '@/utils/random';
import { Model as Building1 } from './generated/village/building-1';
import { Model as Building2 } from './generated/village/building-2';
import { Model as Building3 } from './generated/village/building-3';
import { Model as Building4 } from './generated/village/building-4';
import { Model as BuildingShape1 } from './generated/village/building-shape-1';
import { Model as BuildingShape2 } from './generated/village/building-shape-2';
import { Model as BuildingShape3TwoStory } from './generated/village/building-shape-3-2-story';
import { Model as Chimny } from './generated/village/chimny';
import { Model as Gazeebo } from './generated/village/gazeebo';
import { Model as Tower } from './generated/village/tower';

interface BuildingProps {
  archetype: BuildingArchetype;
  position: [number, number, number];
  rotation?: number;
  label?: string;
}

// Village pack building variants, as typed <Model> components generated by
// gltfjsx against the per-node GLBs split out of Village_Buildings.glb.
// Picking a variant is deterministic on (label, position) so the same
// settlement always produces the same skyline across loads.
const VARIANTS = [
  Building1,
  Building2,
  Building3,
  Building4,
  BuildingShape1,
  BuildingShape2,
  BuildingShape3TwoStory,
];

// Larger buildings that read as town-scale landmarks — pick from this pool
// when the archetype id matches a civic / lodging building.
const LANDMARK_VARIANTS: Record<string, React.ComponentType<React.JSX.IntrinsicElements['group']>> = {
  inn: Building4,
  tavern: Building4,
  chapel: Tower,
  temple: Tower,
  manor: BuildingShape3TwoStory,
  library: BuildingShape3TwoStory,
  barracks: BuildingShape2,
  watchtower: Tower,
  prison: Tower,
};

export function Building({
  archetype,
  position,
  rotation = 0,
  label = '',
}: BuildingProps) {
  const seed = useMemo(
    () => hashString(`${label}-${position[0]}-${position[2]}`),
    [label, position],
  );

  const Variant =
    LANDMARK_VARIANTS[archetype.id] ?? VARIANTS[seed % VARIANTS.length];

  const rotY = (rotation * Math.PI) / 180;
  const decorate = archetype.id === 'inn' || archetype.id === 'tavern';

  return (
    <group position={position} rotation={[0, rotY, 0]}>
      <Variant />
      {decorate && (
        <>
          <Chimny position={[0, 2, 0]} />
          <Gazeebo position={[3, 0, 1]} scale={0.6} />
        </>
      )}
    </group>
  );
}
