import { useMemo } from 'react';
import { hashString } from '@/core';
import { Model as Barrel1 } from './generated/crates/barrel-1';
import { Model as Barrel1Open } from './generated/crates/barrel-1-open';
import { Model as Barrel2Keg } from './generated/crates/barrel-2-keg';
import { Model as Chest1 } from './generated/crates/chest-1';
import { Model as Crate1 } from './generated/crates/crate-1';
import { Model as Crate1Open } from './generated/crates/crate-1-open';
import { Model as Crate2 } from './generated/crates/crate-2';
import { Model as CrateBroken } from './generated/crates/crate-broken';
import { Model as Cart } from './generated/mine/cart';
import { Model as CartRusty } from './generated/mine/cart-rusty';
import { Model as Crystal } from './generated/mine/crystal';
import { Model as CrystalSource } from './generated/mine/crystal-source';
import { Model as Pickaxe } from './generated/mine/pickaxe';
import { Model as RockPile } from './generated/mine/rockpile';
import { Model as RockPile2 } from './generated/mine/rockpile2';
import { Model as Rope } from './generated/mine/rope';
import { Model as RopePile } from './generated/mine/rope-pile';
import { Model as Sack1 } from './generated/mine/sack1';

type PropType = 'crystal' | 'rope' | 'crate' | 'barrel' | 'chest' | 'random';

interface DungeonPropProps {
  id: string;
  type: PropType;
  position: [number, number, number];
  rotation?: number;
}

type GroupComponent = React.ComponentType<React.JSX.IntrinsicElements['group']>;

// Prop pools per semantic type. All variants are typed <Model> components
// generated by gltfjsx against the split GLBs in
// public/assets/dungeon/{crates,mine}/.
const POOLS: Record<Exclude<PropType, 'random'>, GroupComponent[]> = {
  crystal: [Crystal, CrystalSource, Pickaxe, RockPile, RockPile2],
  rope: [Rope, RopePile, Sack1, Cart, CartRusty],
  crate: [Crate1, Crate1Open, Crate2, CrateBroken],
  barrel: [Barrel1, Barrel1Open, Barrel2Keg],
  chest: [Chest1],
};

const RANDOM_POOL: Exclude<PropType, 'random'>[] = [
  'crystal',
  'rope',
  'crate',
  'barrel',
  'chest',
];

export function DungeonProp({
  id,
  type,
  position,
  rotation = 0,
}: DungeonPropProps) {
  const seed = useMemo(() => hashString(id), [id]);
  const resolvedType: Exclude<PropType, 'random'> =
    type === 'random' ? RANDOM_POOL[seed % RANDOM_POOL.length] : type;

  const pool = POOLS[resolvedType];
  const Variant = pool[seed % pool.length];
  const scale = 1 + (seed % 4) * 0.08;

  return (
    <group position={position} rotation={[0, rotation, 0]}>
      <Variant scale={scale} />
    </group>
  );
}
