/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/monsters/Skeleton_warrior.glb -o src/game/components/Skeleton.tsx --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'A-Pose' | 'A-Pose.001' | 'Death_1' | 'Death_2' | 'Hit_1' | 'Hit_2' | 'Idle_1' | 'Idle_1_break' | 'Idle_2' | 'Roar' | 'Sword_attack_1' | 'Sword_attack_2' | 'Sword_attack_3_combo' | 'Unarmed_attack_1' | 'Unarmmed_Attack_2' | 'Walk_1' | 'Walk_2'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Scimitar_MEDIUM: THREE.Mesh
    calf_l: THREE.SkinnedMesh
    calf_r: THREE.SkinnedMesh
    Chest_Armor_1: THREE.SkinnedMesh
    Chest_Armor_2: THREE.SkinnedMesh
    Chest_Armor_3: THREE.SkinnedMesh
    foot_l: THREE.SkinnedMesh
    foot_r: THREE.SkinnedMesh
    hand_l: THREE.SkinnedMesh
    hand_r: THREE.SkinnedMesh
    Helmet_1: THREE.SkinnedMesh
    Helmet_2: THREE.SkinnedMesh
    Helmet_3: THREE.SkinnedMesh
    lower_arm_l: THREE.SkinnedMesh
    lower_arm_r: THREE.SkinnedMesh
    Pelvis: THREE.SkinnedMesh
    jaw: THREE.SkinnedMesh
    skull: THREE.SkinnedMesh
    spine: THREE.SkinnedMesh
    thigh_l: THREE.SkinnedMesh
    thigh_r: THREE.SkinnedMesh
    Torso: THREE.SkinnedMesh
    upper_arm_l: THREE.SkinnedMesh
    upper_arm_r: THREE.SkinnedMesh
    Root: THREE.Bone
    hand_ikL: THREE.Bone
    knee_ikL: THREE.Bone
    Heel_ikL: THREE.Bone
    elbow_ikL: THREE.Bone
    hand_ikR: THREE.Bone
    knee_ikR: THREE.Bone
    Heel_ikR: THREE.Bone
    elbow_ikR: THREE.Bone
  }
  materials: {
    Weapon_Armor: THREE.MeshStandardMaterial
    Skeleton_warrior_2: THREE.MeshStandardMaterial
    Weapon_Armor: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useGLTF('/Skeleton_warrior.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Skeleton_Warrior" rotation={[0, 0, -Math.PI]} scale={-1}>
          <primitive object={nodes.Root} />
          <primitive object={nodes.hand_ikL} />
          <primitive object={nodes.knee_ikL} />
          <primitive object={nodes.Heel_ikL} />
          <primitive object={nodes.elbow_ikL} />
          <primitive object={nodes.hand_ikR} />
          <primitive object={nodes.knee_ikR} />
          <primitive object={nodes.Heel_ikR} />
          <primitive object={nodes.elbow_ikR} />
          <skinnedMesh name="calf_l" geometry={nodes.calf_l.geometry} material={materials.Skeleton_warrior_2} skeleton={nodes.calf_l.skeleton} />
          <skinnedMesh name="calf_r" geometry={nodes.calf_r.geometry} material={materials.Skeleton_warrior_2} skeleton={nodes.calf_r.skeleton} />
          <skinnedMesh name="Chest_Armor_1" geometry={nodes.Chest_Armor_1.geometry} material={materials.Weapon_Armor} skeleton={nodes.Chest_Armor_1.skeleton} />
          <skinnedMesh name="Chest_Armor_2" geometry={nodes.Chest_Armor_2.geometry} material={materials.Weapon_Armor} skeleton={nodes.Chest_Armor_2.skeleton} />
          <skinnedMesh name="Chest_Armor_3" geometry={nodes.Chest_Armor_3.geometry} material={materials.Weapon_Armor} skeleton={nodes.Chest_Armor_3.skeleton} />
          <skinnedMesh name="foot_l" geometry={nodes.foot_l.geometry} material={materials.Skeleton_warrior_2} skeleton={nodes.foot_l.skeleton} />
          <skinnedMesh name="foot_r" geometry={nodes.foot_r.geometry} material={materials.Skeleton_warrior_2} skeleton={nodes.foot_r.skeleton} />
          <skinnedMesh name="hand_l" geometry={nodes.hand_l.geometry} material={materials.Skeleton_warrior_2} skeleton={nodes.hand_l.skeleton} />
          <skinnedMesh name="hand_r" geometry={nodes.hand_r.geometry} material={materials.Skeleton_warrior_2} skeleton={nodes.hand_r.skeleton} />
          <skinnedMesh name="Helmet_1" geometry={nodes.Helmet_1.geometry} material={materials.Weapon_Armor} skeleton={nodes.Helmet_1.skeleton} />
          <skinnedMesh name="Helmet_2" geometry={nodes.Helmet_2.geometry} material={materials.Weapon_Armor} skeleton={nodes.Helmet_2.skeleton} />
          <skinnedMesh name="Helmet_3" geometry={nodes.Helmet_3.geometry} material={materials.Weapon_Armor} skeleton={nodes.Helmet_3.skeleton} />
          <skinnedMesh name="lower_arm_l" geometry={nodes.lower_arm_l.geometry} material={materials.Skeleton_warrior_2} skeleton={nodes.lower_arm_l.skeleton} />
          <skinnedMesh name="lower_arm_r" geometry={nodes.lower_arm_r.geometry} material={materials.Skeleton_warrior_2} skeleton={nodes.lower_arm_r.skeleton} />
          <skinnedMesh name="Pelvis" geometry={nodes.Pelvis.geometry} material={materials.Skeleton_warrior_2} skeleton={nodes.Pelvis.skeleton} />
          <skinnedMesh name="jaw" geometry={nodes.jaw.geometry} material={materials.Skeleton_warrior_2} skeleton={nodes.jaw.skeleton} />
          <skinnedMesh name="skull" geometry={nodes.skull.geometry} material={materials.Skeleton_warrior_2} skeleton={nodes.skull.skeleton} />
          <skinnedMesh name="spine" geometry={nodes.spine.geometry} material={materials.Skeleton_warrior_2} skeleton={nodes.spine.skeleton} />
          <skinnedMesh name="thigh_l" geometry={nodes.thigh_l.geometry} material={materials.Skeleton_warrior_2} skeleton={nodes.thigh_l.skeleton} />
          <skinnedMesh name="thigh_r" geometry={nodes.thigh_r.geometry} material={materials.Skeleton_warrior_2} skeleton={nodes.thigh_r.skeleton} />
          <skinnedMesh name="Torso" geometry={nodes.Torso.geometry} material={materials.Skeleton_warrior_2} skeleton={nodes.Torso.skeleton} />
          <skinnedMesh name="upper_arm_l" geometry={nodes.upper_arm_l.geometry} material={materials.Skeleton_warrior_2} skeleton={nodes.upper_arm_l.skeleton} />
          <skinnedMesh name="upper_arm_r" geometry={nodes.upper_arm_r.geometry} material={materials.Skeleton_warrior_2} skeleton={nodes.upper_arm_r.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Skeleton_warrior.glb')
