/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/npcs/villagers.glb -o src/game/components/Villagers.tsx --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'Emote_No_Additivve(head_only)' | 'Emote_Wave' | 'Emote_Yes_Additivve(head_only)' | 'Idle_1' | 'Idle_2' | 'Idle_Old' | 'Idle_to_sit' | 'Sitting' | 'Talk_1' | 'Talk_Old' | 'TPose' | 'Walk_1' | 'Walk_2_f' | 'Walk_Old'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Male_1: THREE.SkinnedMesh
    Male_2: THREE.SkinnedMesh
    Male_3: THREE.SkinnedMesh
    Male_4: THREE.SkinnedMesh
    Woman_1: THREE.SkinnedMesh
    Woman_2: THREE.SkinnedMesh
    Woman_3: THREE.SkinnedMesh
    Woman_4: THREE.SkinnedMesh
    spine: THREE.Bone
    root: THREE.Bone
    ['MCH-torsoparent']: THREE.Bone
    ['MCH-hand_ikparentL']: THREE.Bone
    ['MCH-upper_arm_ik_targetparentL']: THREE.Bone
    ['MCH-hand_ikparentR']: THREE.Bone
    ['MCH-upper_arm_ik_targetparentR']: THREE.Bone
    ['MCH-foot_ikparentL']: THREE.Bone
    ['MCH-thigh_ik_targetparentL']: THREE.Bone
    ['MCH-foot_ikparentR']: THREE.Bone
    ['MCH-thigh_ik_targetparentR']: THREE.Bone
  }
  materials: {
    Armor: THREE.MeshStandardMaterial
    Male_2: THREE.MeshStandardMaterial
    Male_3: THREE.MeshStandardMaterial
    male_4: THREE.MeshStandardMaterial
    Woman_1: THREE.MeshStandardMaterial
    Woman_2: THREE.MeshStandardMaterial
    Woman_3: THREE.MeshStandardMaterial
    ['Woman_1.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useGLTF('/villagers.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="metarig-noimp">
          <primitive object={nodes.spine} />
        </group>
        <group name="rig">
          <primitive object={nodes.root} />
          <primitive object={nodes['MCH-torsoparent']} />
          <primitive object={nodes['MCH-hand_ikparentL']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentL']} />
          <primitive object={nodes['MCH-hand_ikparentR']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentR']} />
          <primitive object={nodes['MCH-foot_ikparentL']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentL']} />
          <primitive object={nodes['MCH-foot_ikparentR']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentR']} />
          <skinnedMesh name="Male_1" geometry={nodes.Male_1.geometry} material={materials.Armor} skeleton={nodes.Male_1.skeleton} />
          <skinnedMesh name="Male_2" geometry={nodes.Male_2.geometry} material={materials.Male_2} skeleton={nodes.Male_2.skeleton} />
          <skinnedMesh name="Male_3" geometry={nodes.Male_3.geometry} material={materials.Male_3} skeleton={nodes.Male_3.skeleton} />
          <skinnedMesh name="Male_4" geometry={nodes.Male_4.geometry} material={materials.male_4} skeleton={nodes.Male_4.skeleton} />
          <skinnedMesh name="Woman_1" geometry={nodes.Woman_1.geometry} material={materials.Woman_1} skeleton={nodes.Woman_1.skeleton} />
          <skinnedMesh name="Woman_2" geometry={nodes.Woman_2.geometry} material={materials.Woman_2} skeleton={nodes.Woman_2.skeleton} />
          <skinnedMesh name="Woman_3" geometry={nodes.Woman_3.geometry} material={materials.Woman_3} skeleton={nodes.Woman_3.skeleton} />
          <skinnedMesh name="Woman_4" geometry={nodes.Woman_4.geometry} material={materials['Woman_1.001']} skeleton={nodes.Woman_4.skeleton} />
        </group>
        <group name="WGT-rig_spine_fk" position={[0, 1.38, -0.021]} rotation={[1.823, 0, 0]} scale={0.182} />
        <group name="WGT-rig_spine_fk001" position={[0, 1.542, 0]} rotation={[1.694, 0, 0]} scale={0.163} />
        <group name="WGT-rig_spine_fk002" position={[0, 1.542, 0]} rotation={[1.539, 0, 0]} scale={0.206} />
        <group name="WGT-rig_spine_fk003" position={[0, 1.748, -0.007]} rotation={[1.542, 0, 0]} scale={0.23} />
        <group name="WGT-rig_tweak_spine" position={[0, 1.205, -0.066]} rotation={[1.823, 0, 0]} scale={0.091} />
        <group name="WGT-rig_tweak_spine001" position={[0, 1.38, -0.021]} rotation={[1.694, 0, 0]} scale={0.081} />
        <group name="WGT-rig_tweak_spine002" position={[0, 1.542, 0]} rotation={[1.539, 0, 0]} scale={0.103} />
        <group name="WGT-rig_tweak_spine003" position={[0, 1.748, -0.007]} rotation={[1.542, 0, 0]} scale={0.115} />
        <group name="WGT-rig_tweak_spine004" position={[0, 1.978, -0.014]} rotation={[1.948, 0, 0]} scale={0.039} />
        <group name="WGT-rig_torso" position={[0, 1.293, -0.043]} scale={0.468} />
        <group name="WGT-rig_hips" position={[0, 1.205, -0.066]} rotation={[1.823, 0, 0]} scale={0.195} />
        <group name="WGT-rig_chest" position={[0, 1.748, -0.007]} rotation={[1.542, 0, 0]} scale={0.26} />
        <group name="WGT-rig_breastL" position={[0.108, 1.793, 0.083]} rotation={[Math.PI, 0, Math.PI]} scale={0.166} />
        <group name="WGT-rig_breastR" position={[-0.108, 1.793, 0.083]} rotation={[0, 0, Math.PI]} scale={-0.166} />
        <group name="WGT-rig_shoulderL" position={[0.022, 1.915, 0.082]} rotation={[0.103, -0.865, 0.084]} scale={0.164} />
        <group name="WGT-rig_upper_arm_parentL" position={[0.168, 1.924, -0.009]} rotation={[0.417, -1.524, -1.164]} scale={0.111} />
        <group name="WGT-rig_upper_arm_fkL" position={[0.168, 1.924, -0.009]} rotation={[0.417, -1.524, -1.164]} scale={0.444} />
        <group name="WGT-rig_forearm_fkL" position={[0.611, 1.933, -0.028]} rotation={[2.999, -1.451, 1.416]} scale={0.318} />
        <group name="WGT-rig_hand_fkL" position={[0.927, 1.938, 0.01]} rotation={[-1.324, -1.462, -2.904]} scale={0.227} />
        <group name="WGT-rig_upper_arm_ikL" position={[0.168, 1.924, -0.009]} rotation={[0.417, -1.524, -1.164]} scale={0.444} />
        <group name="WGT-rig_upper_arm_ik_targetL" position={[0.63, 1.941, -0.787]} rotation={[-3.13, 0.024, 2.274]} scale={0.095} />
        <group name="WGT-rig_hand_ikL" position={[0.927, 1.938, 0.01]} rotation={[-1.324, -1.462, -2.904]} scale={0.227} />
        <group name="WGT-rig_VIS_upper_arm_ik_poleL" position={[0.611, 1.933, -0.028]} rotation={[Math.PI / 2, 0, -1.565]} scale={0.759} />
        <group name="WGT-rig_upper_arm_tweakL" position={[0.168, 1.924, -0.009]} rotation={[0.417, -1.524, -1.164]} scale={0.111} />
        <group name="WGT-rig_upper_arm_tweakL001" position={[0.389, 1.929, -0.018]} rotation={[0.417, -1.524, -1.164]} scale={0.111} />
        <group name="WGT-rig_forearm_tweakL" position={[0.611, 1.933, -0.028]} rotation={[2.999, -1.451, 1.416]} scale={0.08} />
        <group name="WGT-rig_forearm_tweakL001" position={[0.769, 1.936, -0.009]} rotation={[2.999, -1.451, 1.416]} scale={0.08} />
        <group name="WGT-rig_hand_tweakL" position={[0.927, 1.938, 0.01]} rotation={[-1.324, -1.462, -2.904]} scale={0.057} />
        <group name="WGT-rig_shoulderR" position={[-0.022, 1.915, 0.082]} rotation={[-3.039, -0.865, 0.084]} scale={-0.164} />
        <group name="WGT-rig_upper_arm_parentR" position={[-0.168, 1.924, -0.009]} rotation={[-2.724, -1.524, -1.164]} scale={-0.111} />
        <group name="WGT-rig_upper_arm_fkR" position={[-0.168, 1.924, -0.009]} rotation={[-2.724, -1.524, -1.164]} scale={-0.444} />
        <group name="WGT-rig_forearm_fkR" position={[-0.611, 1.933, -0.028]} rotation={[-0.143, -1.451, 1.416]} scale={-0.318} />
        <group name="WGT-rig_hand_fkR" position={[-0.927, 1.938, 0.01]} rotation={[1.818, -1.462, -2.904]} scale={-0.227} />
        <group name="WGT-rig_upper_arm_ikR" position={[-0.168, 1.924, -0.009]} rotation={[-2.724, -1.524, -1.164]} scale={-0.444} />
        <group name="WGT-rig_upper_arm_ik_targetR" position={[-0.63, 1.941, -0.787]} rotation={[0.011, 0.024, 2.274]} scale={-0.095} />
        <group name="WGT-rig_hand_ikR" position={[-0.927, 1.938, 0.01]} rotation={[1.818, -1.462, -2.904]} scale={-0.227} />
        <group name="WGT-rig_VIS_upper_arm_ik_poleR" position={[-0.611, 1.933, -0.028]} rotation={[-Math.PI / 2, 0, -1.565]} scale={-0.759} />
        <group name="WGT-rig_upper_arm_tweakR" position={[-0.168, 1.924, -0.009]} rotation={[-2.724, -1.524, -1.164]} scale={-0.111} />
        <group name="WGT-rig_upper_arm_tweakR001" position={[-0.389, 1.929, -0.018]} rotation={[-2.724, -1.524, -1.164]} scale={-0.111} />
        <group name="WGT-rig_forearm_tweakR" position={[-0.611, 1.933, -0.028]} rotation={[-0.143, -1.451, 1.416]} scale={-0.08} />
        <group name="WGT-rig_forearm_tweakR001" position={[-0.769, 1.936, -0.009]} rotation={[-0.143, -1.451, 1.416]} scale={-0.08} />
        <group name="WGT-rig_hand_tweakR" position={[-0.927, 1.938, 0.01]} rotation={[1.818, -1.462, -2.904]} scale={-0.057} />
        <group name="WGT-rig_neck" position={[0, 1.978, -0.014]} rotation={[1.856, 0, 0]} scale={0.153} />
        <group name="WGT-rig_head" position={[0, 2.125, 0.029]} rotation={[Math.PI / 2, 0, 0]} scale={0.237} />
        <group name="WGT-rig_tweak_spine005" position={[0, 2.051, 0.016]} rotation={[1.758, 0, 0]} scale={0.037} />
        <group name="WGT-rig_thigh_parentL" position={[0.117, 1.279, -0.015]} rotation={[-1.649, -0.003, 0.033]} scale={0.157} />
        <group name="WGT-rig_thigh_fkL" position={[0.117, 1.279, -0.015]} rotation={[-1.649, -0.003, 0.033]} scale={0.627} />
        <group name="WGT-rig_shin_fkL" position={[0.119, 0.654, 0.034]} rotation={[-1.474, 0.003, 0.033]} scale={0.555} />
        <group name="WGT-rig_foot_fkL" position={[0.117, 0.102, -0.019]} rotation={[-2.583, 0, 0]} scale={0.154} />
        <group name="WGT-rig_toe_fkL" position={[0.117, 0.02, 0.111]} rotation={[Math.PI, 0, Math.PI]} scale={0.08} />
        <group name="WGT-rig_thigh_ikL" position={[0.117, 1.279, -0.015]} rotation={[-1.649, -0.003, 0.033]} scale={0.627} />
        <group name="WGT-rig_thigh_ik_targetL" position={[0.158, 0.649, 1.211]} rotation={[0.004, 0.033, 0]} scale={0.147} />
        <group name="WGT-rig_foot_ikL" position={[0.117, 0.102, -0.019]} scale={0.154} />
        <group name="WGT-rig_VIS_thigh_ik_poleL" position={[0.119, 0.654, 0.034]} rotation={[Math.PI / 2, 0, 0.03]} scale={1.177} />
        <group name="WGT-rig_thigh_tweakL" position={[0.117, 1.279, -0.015]} rotation={[-1.649, -0.003, 0.033]} scale={0.157} />
        <group name="WGT-rig_thigh_tweakL001" position={[0.118, 0.966, 0.01]} rotation={[-1.649, -0.003, 0.033]} scale={0.157} />
        <group name="WGT-rig_shin_tweakL" position={[0.119, 0.654, 0.034]} rotation={[-1.474, 0.003, 0.033]} scale={0.139} />
        <group name="WGT-rig_shin_tweakL001" position={[0.118, 0.378, 0.007]} rotation={[-1.474, 0.003, 0.033]} scale={0.139} />
        <group name="WGT-rig_foot_tweakL" position={[0.117, 0.102, -0.019]} rotation={[-2.583, 0, 0]} scale={0.039} />
        <group name="WGT-rig_foot_spin_ikL" position={[0.117, 0.02, 0.111]} scale={0.077} />
        <group name="WGT-rig_foot_heel_ikL" position={[0.117, 0.102, -0.019]} scale={0.077} />
        <group name="WGT-rig_toe_ikL" position={[0.117, 0.02, 0.111]} rotation={[Math.PI, 0, Math.PI]} scale={0.08} />
        <group name="WGT-rig_thigh_parentR" position={[-0.117, 1.279, -0.015]} rotation={[1.493, -0.003, 0.033]} scale={-0.157} />
        <group name="WGT-rig_thigh_fkR" position={[-0.117, 1.279, -0.015]} rotation={[1.493, -0.003, 0.033]} scale={-0.627} />
        <group name="WGT-rig_shin_fkR" position={[-0.119, 0.654, 0.034]} rotation={[1.667, 0.003, 0.033]} scale={-0.555} />
        <group name="WGT-rig_foot_fkR" position={[-0.117, 0.102, -0.019]} rotation={[0.559, 0, 0]} scale={-0.154} />
        <group name="WGT-rig_toe_fkR" position={[-0.117, 0.02, 0.111]} rotation={[0, 0, -Math.PI]} scale={-0.08} />
        <group name="WGT-rig_thigh_ikR" position={[-0.117, 1.279, -0.015]} rotation={[1.493, -0.003, 0.033]} scale={-0.627} />
        <group name="WGT-rig_thigh_ik_targetR" position={[-0.158, 0.649, 1.211]} rotation={[-3.138, 0.033, 0]} scale={-0.147} />
        <group name="WGT-rig_foot_ikR" position={[-0.117, 0.102, -0.019]} rotation={[-Math.PI, 0, 0]} scale={-0.154} />
        <group name="WGT-rig_VIS_thigh_ik_poleR" position={[-0.119, 0.654, 0.034]} rotation={[-Math.PI / 2, 0, 0.03]} scale={-1.177} />
        <group name="WGT-rig_thigh_tweakR" position={[-0.117, 1.279, -0.015]} rotation={[1.493, -0.003, 0.033]} scale={-0.157} />
        <group name="WGT-rig_thigh_tweakR001" position={[-0.118, 0.966, 0.01]} rotation={[1.493, -0.003, 0.033]} scale={-0.157} />
        <group name="WGT-rig_shin_tweakR" position={[-0.119, 0.654, 0.034]} rotation={[1.667, 0.003, 0.033]} scale={-0.139} />
        <group name="WGT-rig_shin_tweakR001" position={[-0.118, 0.378, 0.007]} rotation={[1.667, 0.003, 0.033]} scale={-0.139} />
        <group name="WGT-rig_foot_tweakR" position={[-0.117, 0.102, -0.019]} rotation={[0.559, 0, 0]} scale={-0.039} />
        <group name="WGT-rig_foot_spin_ikR" position={[-0.117, 0.02, 0.111]} rotation={[-Math.PI, 0, 0]} scale={-0.077} />
        <group name="WGT-rig_foot_heel_ikR" position={[-0.117, 0.102, -0.019]} rotation={[-Math.PI, 0, 0]} scale={-0.077} />
        <group name="WGT-rig_toe_ikR" position={[-0.117, 0.02, 0.111]} rotation={[0, 0, -Math.PI]} scale={-0.08} />
        <group name="WGT-rig_root" scale={1.171} />
      </group>
    </group>
  )
}

useGLTF.preload('/villagers.glb')
